# Generated by Django 4.2.4 on 2023-08-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='valor',
            field=models.FloatField(default=1, verbose_name='Valor do depósito'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conta',
            name='icone',
            field=models.ImageField(upload_to='Icone', verbose_name='Ícone do banco'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='tipo',
            field=models.CharField(choices=[('pf', 'Pessoa Fisica'), ('pj', 'Pessoa Juridica')], max_length=2, verbose_name='Tipo de pessoa'),
        ),
    ]
